### ISSUE TITLE
kiwi_generator cannot be used with newer analyzers 

### ISSUE THREAD

**Issue by bummsa** [gbtb16/kiwi#117]
Hi all,

I have problems when I try to use realm library with realm (and realm_generator) because of the version mismatch for the analyzer lib.

> Because realm_generator >=1.6.1 depends on analyzer ^6.0.0 and kiwi_generator 4.1.0 depends on analyzer ^5.4.0, realm_generator >=1.6.1 is incompatible with kiwi_generator 4.1.0.
So, because shared_proj depends on both kiwi_generator 4.1.0 and realm_generator 3.0.0, version solving failed.

Cheers
Bummsa

**Comment by jk-hub** [comment]
same issue have any found any solution on it ?

**Comment by bummsa** [comment]
No, unfortunately not, unless to write the generated codes manually

**Comment by jk-hub** [comment]
hope the new Kiwi generate will also get an update

**Comment by gbtb16** [comment]
Hi @bummsa! Thanks for your contribution to Kiwi.


I recently upgraded kiwi to 5.0 and was finalizing some changes to kiwi_generator to upgrade it to 4.2.0 as well. This would include upgrading all dependencies.

However, since some people have expressed a need for this, I'll release the version 4.2.0 with the new dependency update, and in the future release (5.0) with the other changes I've been working on.

**Comment by jk-hub** [comment]
@gbtb16 when is the new is coming out for kiwi_generator

**Comment by bummsa** [comment]
@gbtb16 That sounds great! When can we expect version 4.2?

**Comment by gbtb16** [comment]
@bummsa, I'm going to update it today. 

Once it's updated, I'll schedule an appointment so we can try to fix your problem as soon as possible.

**Comment by gbtb16** [comment]
Hi @bummsa!

Sorry for the delay in updating the analyzer version. I've been dealing with a number of high priority requests, and because I've been having some problems updating the analyzer version, I left it on standby until I could properly check the version upgrade.

However, I have now upgraded and we now have kiwi version v5.0.1 (fixing pub.dev score issues) and kiwi_generator v4.2.1 (fixing the analyzer and using kiwi version 5.0.1).

If possible, please test them and send us feedback so that we can assess whether the change was actually correct!

Thanks for your contribution.

Translated with DeepL.com (free version)
